server:
  port: 3344

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuckyLearning/myspringcloud.git # Git上面的git仓库名字
