server:
  port: 8081

person:
  lastName: tom
  age: 18
  boss: false
  birthday: 2019/8/19
  email: 798449106@qq.com
  maps: {k1: v1, k2:v2}
  lists:
    - cat
    - dog
    - pig
  dog:
    name: jack
    color: blue
