spring:
  datasource:
    username: learn01
    password: learn01
    url: jdbc:mysql://localhost:3306/testdatabase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
      default-transaction-isolation: 2   #设置默认的隔离级别为读写提交
  cache:   #缓存配置
    type: REDIS
    cache-names: redisCache
  redis:   #Redis配置
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 1000
    port: 6379
    host: 127.0.0.1
    timeout: 1000

#mybatis配置
mybatis:
  config-location: classpath:mapping/*.xml
  type-aliases-package: com.lif.redistest.pojo

#日志级别
logging:
  level:
    root: debug