server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway


eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com # 自定义zuul相关的服务名称信息
    prefer-ip-address: true # 访问路径可以显示ip地址

info:
  app.name: lif-microservicecloud
  company.name: www.lif.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  # 添加真实名与代理的映射
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  # 原真实名的忽略，单个可以具体写，多个用“*”
  # ignored-services: microservicecloud-dept
  ignored-services: "*"
  # 添加统一前缀
  prefix: /lif
